export const LAY_DANH_SACH_PHIM_API = "LAY_DANH_SACH_PHIM_API ";
export const LAY_CHI_TIET_PHIM_API  = "LAY_CHI_TIET_PHIM_API ";
export const LAY_THOI_LUONG_PHIM_TRONG_CHI_TIET_PHIM_API  = 'LAY_THOI_LUONG_PHIM_TRONG_CHI_TIET_PHIM_API ';
export const LAY_THONG_TIN_HE_THONG_RAP_API  = 'LAY_THONG_TIN_HE_THONG_RAP_API ';
export const LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG_API  = 'LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG_API ';
export const LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP_API  = 'LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP_API ';
export const LAY_DANH_SACH_PHONG_VE_API  = 'LAY_DANH_SACH_PHONG_VE_API ';
export const DAT_VE = 'DAT_VE';
export const LAY_DANH_SACH_PHIM_PHAN_TRANG = "LAY_DANH_SACH_PHIM_PHAN_TRANG";
export const DELETE_PHIM = "DELETE_PHIM";


// local
export const DANG_DAT_GHE = 'DANG_DAT_GHE';
export const DAT_VE_THANH_CONG = 'DAT_VE_THANH_CONG';