export const DANG_NHAP = "DANG_NHAP";
export const DANG_KY = 'DANG_KY';
export const DANG_XUAT = "DANG_XUAT";
export const LAY_THONG_TIN_NGUOI_DUNG = 'LAY_THONG_TIN_NGUOI_DUNG';
export const LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG = 'LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG';
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";